sudo: false

language: r

warnings_are_errors: true

env:
  global:
    - TENSORFLOW_TEST_EXAMPLES="1"
  matrix:
    - TF_VERSION="1.3"
    - TF_VERSION="1.4"
    - TF_VERSION="1.5"
    - TF_VERSION="1.6"
    - TF_VERSION="1.8"
    - TF_VERSION="1.9"
    - TF_VERSION="1.10"
    - TF_VERSION="1.11"
    - TF_VERSION="1.12"
    - TF_VERSION="nightly"

os:
  - linux

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - source scripts/travis_install.sh

addons:
  apt:
    packages:
      - openmpi-bin
